feat(TUP-29701): Upgrade eclipse 418
Talend/components pull request #1850
Opened 2021-01-25 08:13 UTC by hzhao-talendbj

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-01-25 09:27 UTC, build-talend-common commented
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/668/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/668/)

2021-01-26 06:58 UTC, wwang-talend commented on core/components-api/src/main/java/org/talend/components/api/component/runtime/JarRuntimeInfo.java
> +    public JarRuntimeInfo(String jarUrlString, String depTxtPath, String runtimeClassName, URLStreamHandler handler) {
make it private if only use it in current class

2021-01-26 07:09 UTC, hzhao-talendbj commented on core/components-api/src/main/java/org/talend/components/api/component/runtime/JarRuntimeInfo.java
> +    public JarRuntimeInfo(String jarUrlString, String depTxtPath, String runtimeClassName, URLStreamHandler handler) {
thanks , I modified it

2021-01-26 07:28 UTC, wwang-talend reviewed
Possible to write a junit for it? to show the usage for that.

2021-01-26 08:15 UTC, build-talend-common commented
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/670/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/670/)

2021-01-26 11:58 UTC, build-talend-common commented
Pull request test result: [failure](https://ci-common.datapwn.com/job/components_pull-request_master/671/) [:x:](https://ci-common.datapwn.com/job/components_pull-request_master/671/)

2021-01-27 01:16 UTC, wwang-talend approved these changes

2021-01-27 01:17 UTC, wwang-talend requested changes
your added junit failed

2021-01-27 02:51 UTC, build-talend-common commented
Pull request test result: [success](https://ci-common.datapwn.com/job/components_pull-request_master/672/) [:star:](https://ci-common.datapwn.com/job/components_pull-request_master/672/)

2021-01-27 06:10 UTC, wwang-talend approved these changes

2021-01-27 06:13 UTC, merged