chore(TDI-50066): tdp trivy scan
Talend/components pull request #2295
Opened 2023-07-17 12:49 UTC by ozhelezniak-talend

**What is the current behavior?** (You can also link to an open issue here)
https://jira.talendforge.org/browse/TDI-50066

**What is the new behavior?**

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows Talend standard
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features) ?
- [ ] The code coverage on new code >75%
- [ ] The new code does not introduce new technical issues (sonar / eslint)

**What kind of change does this PR introduce?**

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build / CI related changes
- [x] Other... Please describe:

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2023-07-17 14:40 UTC, Gby56 requested changes

2023-07-17 14:40 UTC, Gby56 commented on ci/Jenkinsfile-trivy
> +             -F 'engagement_name=trivy-scan_components_tdp' \
```suggestion
             -F 'engagement_name=trivy-sca_components_tdp' \
```

2023-07-17 14:40 UTC, Gby56 commented on ci/Jenkinsfile-trivy
> +             trivy repo --branch maintenance/tdp https://github.com/Talend/components -f json --scanners vuln -o trivy-results.json --exit-code 0
Would be better to use the rootfs scanning mode
`trivy rootfs \$warfile -f json --security-checks vuln --offline-scan -o trivy-results.json --exit-code 0`

2023-07-18 09:47 UTC, ozhelezniak-talend commented on ci/Jenkinsfile-trivy
> +             trivy repo --branch maintenance/tdp https://github.com/Talend/components -f json --scanners vuln -o trivy-results.json --exit-code 0
okay, I found that it uses services.zip, so we may test it

2023-07-18 10:05 UTC, Gby56 approved these changes

2023-07-18 11:01 UTC, merged